/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAkceRouteImport } from './routes/_authenticated/akce'
import { Route as AuthenticatedHonorareRouteImport } from './routes/_authenticated/honorare'
import { Route as AuthenticatedKalendarRouteImport } from './routes/_authenticated/kalendar'
import { Route as AuthenticatedKarieraRouteImport } from './routes/_authenticated/kariera'
import { Route as AuthenticatedKostymyRouteImport } from './routes/_authenticated/kostymy'
import { Route as AuthenticatedLogistikaRouteImport } from './routes/_authenticated/logistika'
import { Route as AuthenticatedMaterialyRouteImport } from './routes/_authenticated/materialy'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedPripravaRouteImport } from './routes/_authenticated/priprava'
import { Route as AuthenticatedProjektyRouteImport } from './routes/_authenticated/projekty'
import { Route as AuthenticatedReflexeRouteImport } from './routes/_authenticated/reflexe'
import { Route as AuthenticatedRegeneraceRouteImport } from './routes/_authenticated/regenerace'
import { Route as AuthenticatedRiderRouteImport } from './routes/_authenticated/rider'
import { Route as AuthenticatedTreninkRouteImport } from './routes/_authenticated/trenink'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAkceRoute = AuthenticatedAkceRouteImport.update({
  id: '/akce',
  path: '/akce',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHonorareRoute = AuthenticatedHonorareRouteImport.update({
  id: '/honorare',
  path: '/honorare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKalendarRoute = AuthenticatedKalendarRouteImport.update({
  id: '/kalendar',
  path: '/kalendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKarieraRoute = AuthenticatedKarieraRouteImport.update({
  id: '/kariera',
  path: '/kariera',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKostymyRoute = AuthenticatedKostymyRouteImport.update({
  id: '/kostymy',
  path: '/kostymy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogistikaRoute = AuthenticatedLogistikaRouteImport.update({
  id: '/logistika',
  path: '/logistika',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialyRoute = AuthenticatedMaterialyRouteImport.update({
  id: '/materialy',
  path: '/materialy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPripravaRoute = AuthenticatedPripravaRouteImport.update({
  id: '/priprava',
  path: '/priprava',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjektyRoute = AuthenticatedProjektyRouteImport.update({
  id: '/projekty',
  path: '/projekty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReflexeRoute = AuthenticatedReflexeRouteImport.update({
  id: '/reflexe',
  path: '/reflexe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegeneraceRoute = AuthenticatedRegeneraceRouteImport.update({
  id: '/regenerace',
  path: '/regenerace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiderRoute = AuthenticatedRiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreninkRoute = AuthenticatedTreninkRouteImport.update({
  id: '/trenink',
  path: '/trenink',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/akce': typeof AuthenticatedAkceRoute
  '/honorare': typeof AuthenticatedHonorareRoute
  '/kalendar': typeof AuthenticatedKalendarRoute
  '/kariera': typeof AuthenticatedKarieraRoute
  '/kostymy': typeof AuthenticatedKostymyRoute
  '/logistika': typeof AuthenticatedLogistikaRoute
  '/materialy': typeof AuthenticatedMaterialyRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/priprava': typeof AuthenticatedPripravaRoute
  '/projekty': typeof AuthenticatedProjektyRoute
  '/reflexe': typeof AuthenticatedReflexeRoute
  '/regenerace': typeof AuthenticatedRegeneraceRoute
  '/rider': typeof AuthenticatedRiderRoute
  '/trenink': typeof AuthenticatedTreninkRoute
}
export interface FileRoutesByTo {
  '/akce': typeof AuthenticatedAkceRoute
  '/honorare': typeof AuthenticatedHonorareRoute
  '/kalendar': typeof AuthenticatedKalendarRoute
  '/kariera': typeof AuthenticatedKarieraRoute
  '/kostymy': typeof AuthenticatedKostymyRoute
  '/logistika': typeof AuthenticatedLogistikaRoute
  '/materialy': typeof AuthenticatedMaterialyRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/priprava': typeof AuthenticatedPripravaRoute
  '/projekty': typeof AuthenticatedProjektyRoute
  '/reflexe': typeof AuthenticatedReflexeRoute
  '/regenerace': typeof AuthenticatedRegeneraceRoute
  '/rider': typeof AuthenticatedRiderRoute
  '/trenink': typeof AuthenticatedTreninkRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/akce': typeof AuthenticatedAkceRoute
  '/_authenticated/honorare': typeof AuthenticatedHonorareRoute
  '/_authenticated/kalendar': typeof AuthenticatedKalendarRoute
  '/_authenticated/kariera': typeof AuthenticatedKarieraRoute
  '/_authenticated/kostymy': typeof AuthenticatedKostymyRoute
  '/_authenticated/logistika': typeof AuthenticatedLogistikaRoute
  '/_authenticated/materialy': typeof AuthenticatedMaterialyRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/priprava': typeof AuthenticatedPripravaRoute
  '/_authenticated/projekty': typeof AuthenticatedProjektyRoute
  '/_authenticated/reflexe': typeof AuthenticatedReflexeRoute
  '/_authenticated/regenerace': typeof AuthenticatedRegeneraceRoute
  '/_authenticated/rider': typeof AuthenticatedRiderRoute
  '/_authenticated/trenink': typeof AuthenticatedTreninkRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akce'
    | '/honorare'
    | '/kalendar'
    | '/kariera'
    | '/kostymy'
    | '/logistika'
    | '/materialy'
    | '/portfolio'
    | '/priprava'
    | '/projekty'
    | '/reflexe'
    | '/regenerace'
    | '/rider'
    | '/trenink'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/akce'
    | '/honorare'
    | '/kalendar'
    | '/kariera'
    | '/kostymy'
    | '/logistika'
    | '/materialy'
    | '/portfolio'
    | '/priprava'
    | '/projekty'
    | '/reflexe'
    | '/regenerace'
    | '/rider'
    | '/trenink'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/akce'
    | '/_authenticated/honorare'
    | '/_authenticated/kalendar'
    | '/_authenticated/kariera'
    | '/_authenticated/kostymy'
    | '/_authenticated/logistika'
    | '/_authenticated/materialy'
    | '/_authenticated/portfolio'
    | '/_authenticated/priprava'
    | '/_authenticated/projekty'
    | '/_authenticated/reflexe'
    | '/_authenticated/regenerace'
    | '/_authenticated/rider'
    | '/_authenticated/trenink'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akce': {
      id: '/_authenticated/akce'
      path: '/akce'
      fullPath: '/akce'
      preLoaderRoute: typeof AuthenticatedAkceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/honorare': {
      id: '/_authenticated/honorare'
      path: '/honorare'
      fullPath: '/honorare'
      preLoaderRoute: typeof AuthenticatedHonorareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalendar': {
      id: '/_authenticated/kalendar'
      path: '/kalendar'
      fullPath: '/kalendar'
      preLoaderRoute: typeof AuthenticatedKalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kariera': {
      id: '/_authenticated/kariera'
      path: '/kariera'
      fullPath: '/kariera'
      preLoaderRoute: typeof AuthenticatedKarieraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kostymy': {
      id: '/_authenticated/kostymy'
      path: '/kostymy'
      fullPath: '/kostymy'
      preLoaderRoute: typeof AuthenticatedKostymyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistika': {
      id: '/_authenticated/logistika'
      path: '/logistika'
      fullPath: '/logistika'
      preLoaderRoute: typeof AuthenticatedLogistikaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materialy': {
      id: '/_authenticated/materialy'
      path: '/materialy'
      fullPath: '/materialy'
      preLoaderRoute: typeof AuthenticatedMaterialyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/priprava': {
      id: '/_authenticated/priprava'
      path: '/priprava'
      fullPath: '/priprava'
      preLoaderRoute: typeof AuthenticatedPripravaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekty': {
      id: '/_authenticated/projekty'
      path: '/projekty'
      fullPath: '/projekty'
      preLoaderRoute: typeof AuthenticatedProjektyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reflexe': {
      id: '/_authenticated/reflexe'
      path: '/reflexe'
      fullPath: '/reflexe'
      preLoaderRoute: typeof AuthenticatedReflexeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regenerace': {
      id: '/_authenticated/regenerace'
      path: '/regenerace'
      fullPath: '/regenerace'
      preLoaderRoute: typeof AuthenticatedRegeneraceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rider': {
      id: '/_authenticated/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof AuthenticatedRiderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trenink': {
      id: '/_authenticated/trenink'
      path: '/trenink'
      fullPath: '/trenink'
      preLoaderRoute: typeof AuthenticatedTreninkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAkceRoute: typeof AuthenticatedAkceRoute
  AuthenticatedHonorareRoute: typeof AuthenticatedHonorareRoute
  AuthenticatedKalendarRoute: typeof AuthenticatedKalendarRoute
  AuthenticatedKarieraRoute: typeof AuthenticatedKarieraRoute
  AuthenticatedKostymyRoute: typeof AuthenticatedKostymyRoute
  AuthenticatedLogistikaRoute: typeof AuthenticatedLogistikaRoute
  AuthenticatedMaterialyRoute: typeof AuthenticatedMaterialyRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedPripravaRoute: typeof AuthenticatedPripravaRoute
  AuthenticatedProjektyRoute: typeof AuthenticatedProjektyRoute
  AuthenticatedReflexeRoute: typeof AuthenticatedReflexeRoute
  AuthenticatedRegeneraceRoute: typeof AuthenticatedRegeneraceRoute
  AuthenticatedRiderRoute: typeof AuthenticatedRiderRoute
  AuthenticatedTreninkRoute: typeof AuthenticatedTreninkRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAkceRoute: AuthenticatedAkceRoute,
  AuthenticatedHonorareRoute: AuthenticatedHonorareRoute,
  AuthenticatedKalendarRoute: AuthenticatedKalendarRoute,
  AuthenticatedKarieraRoute: AuthenticatedKarieraRoute,
  AuthenticatedKostymyRoute: AuthenticatedKostymyRoute,
  AuthenticatedLogistikaRoute: AuthenticatedLogistikaRoute,
  AuthenticatedMaterialyRoute: AuthenticatedMaterialyRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedPripravaRoute: AuthenticatedPripravaRoute,
  AuthenticatedProjektyRoute: AuthenticatedProjektyRoute,
  AuthenticatedReflexeRoute: AuthenticatedReflexeRoute,
  AuthenticatedRegeneraceRoute: AuthenticatedRegeneraceRoute,
  AuthenticatedRiderRoute: AuthenticatedRiderRoute,
  AuthenticatedTreninkRoute: AuthenticatedTreninkRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
